### ISSUE TITLE
Vendor specific host implementation

### ISSUE THREAD

**Issue by Docfch** [shreeve/pico-usb#2]
Hello,

I have three interconnected hubs and on each hub I have connected an STM32 whose USB is in vendor-specific device mode. I want to plug it to a pico w to establish wifi communication through usb.

Is there an example on vendor specific host implementation ?

Thanks.

**Comment by shreeve** [comment]
Hello @Docfch !

Pico USB is a very new project (I just added support for device enumeration last night). However, it is a solid foundation and uses all native pico-sdk libraries. The code base should be quite readable and is very lightweight (it doesn't do too much, yet!). 

I haven't enable support for hubs yet, but will be working on this now. Any help you could offer would be much appreciated.

Thanks!

**Comment by Docfch** [comment]
Hi @shreeve thanks for your reply !
I'm working fully on this project, but actually, i'm an electronic engineer, I'm not an expert in programming nor an expert in USB, but I manage anyway. 
If you can tell me and show me how can i help, it would be great.

**Comment by shreeve** [comment]
The repo has moved to https://github.com/shreeve/picousb
