### ISSUE TITLE
No more updates ?

### ISSUE THREAD

**Issue by maaamcube** [shreeve/pico-usb#3]
Hello everyone,
This library is no more updated ?
Thanks.

**Comment by shreeve** [comment]
Hello @maaamcube - We got extremely close to getting this lightweight USB Host library working. We are able to enumerate devices, but it needs some testing and some beating up on to make sure that everything works as expected. If you have the ability to test it on your hardware, please do. I'll put some work over the weekend to see if we can get it a bit more robust.

**Comment by shreeve** [comment]
@maaamcube - Making great progress on this, should be able to commit something here soon. Of course, it's just the core USB Host stack without all the drivers, etc. but it is a clean, simple, native USB Host implementation. I don't know of any others besides TinyUSB. Hope to have something very soon.

**Comment by maaamcube** [comment]
@shreeve Great !
I'm looking to use it for USB IP to send USB's through Wifi.
Here is my PCB (USB device Vendor Specific): 

![image](https://github.com/user-attachments/assets/7352e27c-22bb-4b15-962e-1c547ced98c7)

**Comment by shreeve** [comment]
The repo has moved to https://github.com/shreeve/picousb
